package SeleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PreviousPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\Priya\\Desktop\\Module 4\\Project\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void previousPage() throws InterruptedException {
    driver.get("http://localhost:8080/kickInTeam26/");
    driver.manage().window().setSize(new Dimension(838, 770));
    driver.findElement(By.id("inputEmail")).sendKeys("hk@gmail.com");
    {
      WebElement element = driver.findElement(By.cssSelector(".btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("inputPassword")).sendKeys("hk");
    driver.findElement(By.cssSelector(".btn")).click();
    Thread.sleep(7000);
//    driver.findElement(By.cssSelector(".glyphicon-user")).click();
    driver.findElement(By.id("users")).click();
    Thread.sleep(7000);
//    driver.findElement(By.cssSelector(".glyphicon-arrow-left")).click();
    driver.findElement(By.id("arrow")).click();
    Thread.sleep(7000);
//    driver.findElement(By.cssSelector(".glyphicon-globe")).click();
    driver.findElement(By.id("maps")).click();
    Thread.sleep(7000);
//    driver.findElement(By.cssSelector(".glyphicon-arrow-left")).click();
    driver.findElement(By.id("arrow")).click();
    Thread.sleep(7000);
//    driver.findElement(By.cssSelector(".glyphicon-cog")).click();
    driver.findElement(By.id("resources")).click();
    Thread.sleep(7000);
//    driver.findElement(By.cssSelector(".glyphicon-arrow-left")).click();
    driver.findElement(By.id("arrow")).click();
    Thread.sleep(7000);
  }
}
