package SeleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestResources {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\Priya\\Desktop\\Module 4\\Project\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testResources() throws InterruptedException {
    driver.get("http://localhost:8080/kickInTeam26/");
    driver.findElement(By.id("inputEmail")).sendKeys("priya@email.com");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("priya");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    Thread.sleep(7000);
    driver.findElement(By.cssSelector(".glyphicon-cog")).click();
    Thread.sleep(7000);
    driver.findElement(By.cssSelector("tr:nth-child(2) .glyphicon-eye-open")).click();
    Thread.sleep(7000);
    driver.findElement(By.cssSelector("#imageModal .close")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .glyphicon-eye-open")).click();
    Thread.sleep(7000);
    driver.findElement(By.cssSelector("#imageModal .close")).click();
    driver.findElement(By.id("searchTable")).click();
    driver.findElement(By.id("searchTable")).sendKeys("skittles");
    Thread.sleep(7000);
    driver.findElement(By.id("searchTable")).clear();
    driver.findElement(By.id("searchTable")).click();
    driver.findElement(By.id("searchTable")).sendKeys("does not exist");
    Thread.sleep(7000);
  }
}
