package SeleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import nl.utwente.di.team26.Constants;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestEvent {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", Constants.CHROME_DRIVER);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testEvent() throws InterruptedException {
    driver.get(Constants.ISSUER);

    // Log in.
    driver.findElement(By.id("inputEmail")).sendKeys("priya@email.com");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("priya");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    Thread.sleep(7000);

    // Add a new event.
    driver.findElement(By.id("addEventBtn")).click();
    driver.findElement(By.id("eventName")).click();
    driver.findElement(By.id("eventName")).sendKeys("Test event");
    driver.findElement(By.id("eventName")).sendKeys(Keys.TAB);
    driver.findElement(By.id("eventDescription")).sendKeys("event test description");
    driver.findElement(By.id("eventDescription")).sendKeys(Keys.TAB);
    driver.findElement(By.id("eventDate")).clear();
    driver.findElement(By.id("eventDate")).sendKeys("2020-06-24");
    driver.findElement(By.id("eventLocation")).click();
    {
      WebElement dropdown = driver.findElement(By.id("eventLocation"));
      dropdown.findElement(By.xpath("//option[. = 'Outside Campus (City)']")).click();
    }
    driver.findElement(By.id("eventLocation")).click();
    driver.findElement(By.cssSelector(".bottomright > .align-self-end")).click();
    Thread.sleep(7000);

    // Edit an event.
    driver.findElement(By.cssSelector("tr:nth-child(2) .glyphicon-pencil")).click();
    Thread.sleep(7000);
    driver.findElement(By.id("eventName")).click();
    driver.findElement(By.id("eventName")).sendKeys("test event edit");
    driver.findElement(By.id("eventName")).sendKeys(Keys.TAB);
    driver.findElement(By.id("eventDescription")).sendKeys("edited");
    driver.findElement(By.id("eventDescription")).sendKeys(Keys.TAB);
    driver.findElement(By.id("eventDate")).clear();
    driver.findElement(By.id("eventDate")).sendKeys("2020-06-30");
    driver.findElement(By.id("eventLocation")).click();
    {
      WebElement dropdown = driver.findElement(By.id("eventLocation"));
      dropdown.findElement(By.xpath("//option[. = 'Both']")).click();
    }
    driver.findElement(By.id("myBtn")).click();
    Thread.sleep(7000);

    // Link map to event.
    driver.findElement(By.id("addMapsToEvent")).click();
    Thread.sleep(7000);
    driver.findElement(By.cssSelector(".custom-control:nth-child(3) > .custom-control-label")).click();
    driver.findElement(By.cssSelector(".bottomright:nth-child(4) > .btn")).click();
    Thread.sleep(7000);

    // View map.
    driver.findElement(By.cssSelector(".glyphicon-eye-open")).click();
    Thread.sleep(7000);

    // Go back to 'list of events' page
    driver.findElement(By.cssSelector(".glyphicon-home")).click();
    Thread.sleep(7000);

    // Try to sort the list of events in the 4 possible ways.
    driver.findElement(By.cssSelector(".dropdown-toggle")).click();
    driver.findElement(By.linkText("A - Z")).click();
    Thread.sleep(7000);
    driver.findElement(By.cssSelector(".dropdown-toggle")).click();
    driver.findElement(By.linkText("Z - A")).click();
    Thread.sleep(7000);
    driver.findElement(By.cssSelector(".dropdown-toggle")).click();
    driver.findElement(By.linkText("Event Date (New - Old)")).click();
    Thread.sleep(7000);
    driver.findElement(By.cssSelector(".dropdown-toggle")).click();
    driver.findElement(By.linkText("Event Date (Old - New)")).click();
    Thread.sleep(7000);

    // Search for an existing event.
    driver.findElement(By.id("searchTable")).click();
    driver.findElement(By.id("searchTable")).clear();
    driver.findElement(By.id("searchTable")).sendKeys("event");
    Thread.sleep(7000);

    // Search for an inexistent event.
    driver.findElement(By.id("searchTable")).click();
    driver.findElement(By.id("searchTable")).clear();
    driver.findElement(By.id("searchTable")).sendKeys("does not exist");
    Thread.sleep(7000);
  }
}
